CREATE TABLE IF NOT EXISTS USER (
   USER_ID    INT NOT NULL AUTO_INCREMENT,
   USER_NAME  VARCHAR(100) NOT NULL UNIQUE,
   FIRST_NAME VARCHAR(100) NOT NULL,
   LAST_NAME  VARCHAR(100) NOT NULL,
   PASSWORD   VARCHAR(100) NOT NULL,
   PRIMARY KEY ( USER_ID )
);

CREATE TABLE IF NOT EXISTS SESSION (
   USER_ID             INT NOT NULL UNIQUE,
   SESSION_TOKEN       VARCHAR(100) NOT NULL,
   CREATION_TIME       DATETIME NOT NULL,
   CREATION_EPOCH_TIME INT NOT NULL,
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS PIZZA (
   PIZZA_TYPE_ID    INT NOT NULL,
   PIZZA_SIZE_ID    INT NOT NULL,
   PIZZA_TOPPING_ID INT NOT NULL,
   FOREIGN KEY (PIZZA_TYPE_ID) REFERENCES PIZZA_TYPE(PIZZA_TYPE_ID),
   FOREIGN KEY (PIZZA_SIZE_ID) REFERENCES PIZZA_SIZE(PIZZA_SIZE_ID),
   FOREIGN KEY (PIZZA_TOPPING_ID) REFERENCES PIZZA_TOPPING(PIZZA_TOPPING_ID)
);

CREATE TABLE IF NOT EXISTS PIZZA_TYPE (
   PIZZA_TYPE_ID INT NOT NULL AUTO_INCREMENT,
   NAME          VARCHAR(100) NOT NULL,
   DESCRIPTION   VARCHAR(1000) NOT NULL,
   PRIMARY KEY ( PIZZA_TYPE_ID )
);

CREATE TABLE IF NOT EXISTS PIZZA_SIZE (
   PIZZA_SIZE_ID INT NOT NULL AUTO_INCREMENT,
   NAME          VARCHAR(100) NOT NULL,
   DESCRIPTION   VARCHAR(1000) NOT NULL,
   PRICE         FLOAT(5,2) NOT NULL,
   PRIMARY KEY ( PIZZ_SIZE_ID )
);

CREATE TABLE IF NOT EXISTS PIZZA_TOPPING (
   PIZZA_TOPPING_ID INT NOT NULL AUTO_INCREMENT,
   NAME             VARCHAR(100) NOT NULL,
   DESCRIPTION      VARCHAR(1000) NOT NULL,
   PRICE            FLOAT(5,2) NOT NULL,
   PRIMARY KEY ( PIZZA_TOPPING_ID ),
);

CREATE TABLE IF NOT EXISTS PURCHASE (
   PURCHASE_ID         INT NOT NULL AUTO_INCREMENT,
   USER_ID             INT NOT NULL,
   TOTAL_AMOUNT        FLOAT(5,2) NOT NULL,
   CREATION_TIME       DATETIME NOT NULL,
   CREATION_EPOCH_TIME INT NOT NULL,
   PRIMARY KEY (PURCHASE_ID),
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS SUB_ITEM_CATEGORY (
   SUB_ITEM_CATEGORY_ID    INT NOT NULL AUTO_INCREMENT,
   SUB_ITEM_NAME           INT NOT NULL
   PRIMARY KEY (SUB_ITEM_CATEGORY_ID),
);

CREATE TABLE IF NOT EXISTS PURCHASE_DETAIL (
   PURCHASE_ID            INT NOT NULL,
   PIZZA_TYPE_ID          INT NOT NULL,
   SUB_ITEM_ID            INT NOT NULL,
   SUB_ITEM_CATEGORY_ID   INT NOT NULL,
   QUANTITY               INT NOT NULL,
   SINGLE_PRICE           FLOAT(5,2) NOT NULL,
   SUB_TOTAL              FLOAT(5,2) NOT NULL,
   FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(PURCHASE_ID)
);
