CREATE TABLE IF NOT EXISTS USER (
   USER_ID    INT NOT NULL AUTO_INCREMENT,
   USER_NAME  VARCHAR(100) NOT NULL,
   FIRST_NAME VARCHAR(100) NOT NULL,
   LAST_NAME  VARCHAR(100) NOT NULL,
   PASSWORD   VARCHAR(100) NOT NULL,
   PRIMARY KEY ( USER_ID )
);

CREATE TABLE IF NOT EXISTS SESSION (
   USER_ID             INT NOT NULL,
   SESSION_TOKEN       VARCHAR(100) NOT NULL,
   CREATION_TIME       DATETIME NOT NULL,
   CREATION_EPOCH_TIME INT NOT NULL,
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS PIZZA (
   PIZZA_ID      INT NOT NULL AUTO_INCREMENT,
   NAME          VARCHAR(100) NOT NULL,
   DESCRIPTION   VARCHAR(1000) NOT NULL,
   PRICE         FLOAT(5,2) NOT NULL,
   PRIMARY KEY ( PIZZA_ID )
);


CREATE TABLE IF NOT EXISTS PURCHASE (
   PURCHASE_ID         INT NOT NULL AUTO_INCREMENT,
   USER_ID             INT NOT NULL,
   CREATION_TIME       DATETIME NOT NULL,
   CREATION_EPOCH_TIME INT NOT NULL,
   PRIMARY KEY (PURCHASE_ID),
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS PURCHASE_DETAIL (
   PURCHASE_ID         INT NOT NULL,
   PIZZA_ID            INT NOT NULL,
   PRICE               FLOAT(5,2) NOT NULL,
   QUANTITY            INT NOT NULL,
   FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(PURCHASE_ID),
   FOREIGN KEY (PIZZA_ID) REFERENCES PIZZA(PIZZA_ID)
);
